assign_public_ip             = "true"
availability_zone            = "eu-west-2a"
instance_type                = "t2.micro"
key_name                     = "timw-contino-eu-west-2"
vpc_cidr                     = "10.0.0.0/16"
public_subnet_cidr           = "10.0.1.0/24"
private_subnet_cidr          = "10.0.2.0/24"